<a href="https://colab.research.google.com/github/AsadiAhmad/Hit-and-Miss/blob/main/Code/Hit_and_Miss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: Import Libraries

In [ ]:
import numpy as np

# Step 2: Define Image with numpy

In [ ]:
image = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                  [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                  [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0],
                  [0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
                  [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]] , dtype=np.int8)

# Step 3: Define Kernels

## Corner kernels

In [ ]:
nw_kernel = np.array([[-1, -1,  0],
                      [-1,  1,  1],
                      [ 0,  1,  0]], dtype=np.int8)

ne_kernel = np.array([[ 0, -1, -1],
                      [ 1,  1, -1],
                      [ 0,  1,  0]], dtype=np.int8)

se_kernel = np.array([[ 0,  1,  0],
                      [ 1,  1, -1],
                      [ 0, -1, -1]], dtype=np.int8)

sw_kernel = np.array([[ 0,  1,  0],
                      [-1,  1,  1],
                      [-1, -1,  0]], dtype=np.int8)

## Edge kernels

In [ ]:
n_kernel = np.array([[-1, -1,  0],
                     [ 1,  1,  0],
                     [ 0,  0,  0]], dtype=np.int8)

e_kernel = np.array([[ 0,  1, -1],
                     [ 0,  1, -1],
                     [ 0,  0,  0]], dtype=np.int8)

s_kernel = np.array([[ 0,  0,  0],
                     [ 0,  1,  1],
                     [ 0, -1, -1]], dtype=np.int8)

w_kernel = np.array([[ 0,  0,  0],
                     [-1,  1,  0],
                     [-1,  1,  0]], dtype=np.int8)

# Step 4: Calculate Hit or Miss

In [ ]:
def calculate_hit_or_miss(image, kernel, condition_sum):
    converted_image = np.where(image == 1, 1, -1).astype(np.int8)
    height, width = converted_image.shape
    matrix = np.zeros((height, width), dtype='int8')
    for i in range(1, height-2):
        for j in range(1, width-2):
            result = converted_image[i-1:i+2, j-1:j+2] * kernel
            result = result.flatten().tolist()
            if sum(result) == condition_sum:
                matrix[i, j] = 1
    return matrix

In [ ]:
matrix1 = calculate_hit_or_miss(image, nw_kernel, 6)
matrix2 = calculate_hit_or_miss(image, ne_kernel, 6)
matrix3 = calculate_hit_or_miss(image, sw_kernel, 6)
matrix4 = calculate_hit_or_miss(image, se_kernel, 6)
matrix5 = calculate_hit_or_miss(image, n_kernel, 4)
matrix6 = calculate_hit_or_miss(image, e_kernel, 4)
matrix7 = calculate_hit_or_miss(image, s_kernel, 4)
matrix8 = calculate_hit_or_miss(image, w_kernel, 4)

# Step 5: Or all Matrices

In [ ]:
matrices_list = [matrix1, matrix2, matrix3, matrix4, matrix5, matrix6, matrix7, matrix8]
final_matrix = matrices_list[0].copy()

for mat in matrices_list[1:]:
    final_matrix = np.logical_or(final_matrix, mat)

final_matrix = final_matrix.astype(np.int8)

In [ ]:
print(final_matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
